### ISSUE TITLE
Can't plot the example on my laptop

### ISSUE THREAD

**Issue by anamarta** [anazalea/pySankey#12]
I'm trying to reproduce your fruits example plot and there seems to be a problem with how the DataFrame cases are defined. I got this error:

```
File "..\anaconda3/lib/python3.6/site-packages/pySankey-1.0.0-py3.6.egg/pysankey/sankey.py", line 107, in sankey
    raise NullsInFrame('Sankey graph does not support null values.')
  File "..\anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

I just tried to plot the first diagram, without any change, using the fruits.txt file.

**Comment by Pierre-Sassoulas** [comment]
This is because of me, I added a regression without realizing. Use the fix on my branch [here](https://github.com/Pierre-Sassoulas/pySankey). [This PR](https://github.com/anazalea/pySankey/pull/10) should fix the problem.
