### ISSUE TITLE
Weighted sankay example

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [anazalea/pySankey#13]
Hi @marcomanz,

I tried to integrate your change to the common pysankey repository, and now I want to test them, but I fail to reproduce your weighted example. What I tried is this : 

```
import pandas as pd
from pysankey import sankey

df = pd.read_csv(
    'pysankey/customers-goods.csv', sep=',',
    names=['id', 'customer', 'good', 'revenue']
)
sankey(
    left=df['customer'], right=df['good'], rightWeight=df['revenue'], aspect=20,
    fontsize=20, figureName="customer-good"
)
```

But I get this error : 

```
    myD['bottom'] = rightWidths[rightLabels[i - 1]]['top'] + 0.02 * dataFrame.rightWeight.sum()
TypeError: can't multiply sequence by non-int of type 'float'
```

Do you have any idea what is wrong with my call ? What was your own call to get customer-goods.png, do you still have it ?

Cheers,

**Comment by marcomanz** [comment]
Hi Pierre-Sassoulas,
my original call was with df['customer'].values, etc., to give a numpy array instead of a pandas Series as input. I am not sure this is the problem however.

**Comment by Pierre-Sassoulas** [comment]
@marcomanz , thank you for your answer, I was able to fix it following your answer.

The error disapear if we remove the first row with the text and cast the "weight" array as float. The resulting picture was faulty (everything was crushed to the bottom). Fixed by using the same weights for the left side too :)

```
        weight = self.data['revenue'].values[1:].astype(float)
        sankey(left=self.data['customer'].values[1:], right=self.data['good'].values[1:],
               rightWeight=weight, leftWeight=weight, aspect=20, fontsize=10,
               figureName=self.figure_name)
```
