### ISSUE TITLE
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by brianpenghe** [anazalea/pySankey#31]
After I fixed the len() error, there was another one:
```
/usr/local/lib/python3.6/dist-packages/pysankey/sankey.py in check_data_matches_labels(labels, data, side)
     56             data = set(data.unique().tolist())
     57         if isinstance(labels, list):
---> 58             labels = set(labels)
     59         if labels != data:
     60             msg = "\n"

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Do you know why?

**Comment by Pierre-Sassoulas** [comment]
I don't know, My intuition would be that we're not casting labels to a boolean line 58 so there should not be an error? I'm welcoming pull request [here](https://github.com/pierre-sassoulas/pySankey) if you fix the problem. :)

**Comment by brianpenghe** [comment]
> I don't know, My intuition would be that we're not casting labels to a boolean line 58 so there should not be an error? I'm welcoming pull request [here](https://github.com/pierre-sassoulas/pySankey) if you fix the problem. :)

What do you mean by a boolean line?

**Comment by brianpenghe** [comment]
> I don't know, My intuition would be that we're not casting labels to a boolean line 58 so there should not be an error? I'm welcoming pull request [here](https://github.com/pierre-sassoulas/pySankey) if you fix the problem. :)

I possibly figured out why. I was using a npassay as label
