### ISSUE TITLE
Left side is squeezed

### ISSUE THREAD

**Issue by weirdyang** [anazalea/pySankey#36]
![image](https://user-images.githubusercontent.com/25576022/83348282-a8f2ec80-a35d-11ea-86ea-256289112e58.png)
Hi,

I'm trying the example but the end result has the left side items squeezed together. Is there something wrong with  my code?

**Comment by weirdyang** [comment]
I tried the pySankeyBeta package too and still have the same issue.

**Comment by Pierre-Sassoulas** [comment]
Hello, I don't see anything wrong with you code. Maybe it's a bug. If you manage to fix it do not hesitate to make a pull request. And if you see what's wrong with the code please update this post with the solution :)

**Comment by weirdyang** [comment]
I realised this problem occurs if you set the rightWeight flag. I will try to investigate, thanks.  
  
edit; the leftWEight should be used instead  
  
`sankey.sankey(
    left=df['customer'], right=df['good'], leftWeight=df['revenue'], aspect=20,
    fontsize=20, figureName="customer-good"
)`
